[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

# This ensures client-side routing works correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200